# -------------------
# Site settings
# -------------------
host: "localhost"
url: "https://silviamaggidesign.com"
baseurl: ""
posts_limit: 20
lang: "en-GB"
title: Silvia Maggi
tagline: Designer
permalink: /:categories/:title/
timezone: Europe/London
logo: /assets/images/silviamaggi-og-image.jpg
smd_latestposts_limit: 5
excerpt_separator: <!--more-->

# -------------------
# Personal data
# -------------------
author:
  name: Silvia Maggi
  email: hello@silviamaggidesign.com
  smd_avatar_src: /assets/images/silviamaggi-avatar.png

# -------------------
# About
# -------------------
description: 'Welcome to my personal website. I write about design, technology, their effects on our lives, photography, and more. I curate the inspiration series <em>Design, Digested</em>.'
keywords:
  UX design,
  web design,
  accessibility,
  interaction design,
  web standards,
  web development,
  usability,
  information architecture,
  blog,

# -------------------
# Inclusions
# -------------------
include: ["_pages", "assets/js/search.json"]

# -------------------
# SASS
# -------------------
sass:
  sass_dir: /assets/css/partials/
  sourcemap: development

# -------------------
# Markdown
# -------------------
kramdown:
  syntax_highlighter_opts:
    disable: true

# -------------------
# Jekyll defaults
# -------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "jeremybearimies"
    values:
      layout: "jeremy"

# -------------------
# Jekyll collections
# -------------------
collections:
  projects:
    output: true
    permalink: /work/:path/
  newsletters:
    output: true
    permalink: /newsletter/:path/
  jeremybearimies:
    output: true
    permalink: /jeremybearimy/:path/

# -------------------
# Jekyll archives
# -------------------
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
  slug_mode: latin
  date: 2021-08-15 13:45

# -------------------
# Jekyll plugins
# -------------------
plugins:
  - jekyll-archives
  - jekyll-responsive-image

responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
      quality: 80
    - width: 768
      quality: 80
    - width: 1200
      quality: 90
  strip: true
  output_path_format: assets/images/responsive/%{width}/%{basename}