host: "localhost"
url: "https://silviamaggidesign.com"
baseurl: ""
posts_limit: 20

# SEO
title: Silvia Maggi
tagline: Designer
description: 'Welcome to my personal website. I write about about design, technology, their effects on our lives, photography and music. <br>Curator of the inspiration series <em>Design, Digested</em>.'
permalink: /:categories/:title/
keywords:
  UX design,
  web design,
  accessibility,
  interaction design,
  web standards,
  web development,
  WordPress,
  usability,
  information architecture,
timezone: UK/London
logo: /assets/images/silviamaggi-og-image.jpg
author:
  name: Silvia Maggi
  email: hello@silviamaggidesign.com
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: /assets/css/partials/
  sourcemap: development

# Brand
brand:
  smd_avatar_src: /assets/images/silviamaggi-avatar.png
  smd_latestposts_limit: 5

include: ["_pages", "assets/js/search.json"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "jeremybearimies"
    values:
      layout: "jeremy"

# Collections
collections:
  projects:
    output: true
    permalink: /work/:path/
  newsletters:
    output: true
    permalink: /newsletter/:path/
  jeremybearimies:
    output: true
    permalink: /jeremybearimy/:path/

# Taxonomy
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
  slug_mode: latin
  date: 2021-08-15 13:45

excerpt_separator: <!--more-->

# Responsive images
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
      quality: 80
    - width: 768
      quality: 80
    - width: 1200
      quality: 90
  strip: true
  output_path_format: assets/images/responsive/%{width}/%{basename}

# Plugins
plugins:
  - jekyll-archives
  - jekyll-responsive-image