# SEO
title: Silvia Maggi Design
tagline: UX Designer
description: Welcome. Silvia Maggi is a UX Designer striving to create meaningful, user-centric experiences. View her UX portfolio and latest blog posts.
permalink: /:categories/:title/
keywords:
  uxdesign,
  design
timezone: Europe/Rome
logo: /assets/images/silviamaggi-og-image.jpg
author:
  name: Silvia Maggi
  email: hello@silviamaggidesign.com

# Brand
brand:
  smd_avatar_src: /assets/images/silviamaggi-avatar.png
  smd_avatar_alt: Portrait of Silvia Maggi
  smd_tagline: Hi, I’m Silvia
  smd_pitch: A UX Designer striving to create meaningful digital experiences through <strong>User-Centred Design</strong>.
  smd_latestposts_limit: 3

exclude: 
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - build
  - js
  - sass
include: ["_pages"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "jeremybearimies"
    values:
      layout: "jeremy"

# Collections
collections:
  casestudies:
    output: true
    permalink: /portfolio/:path/
  sideprojects:
    output: true
    permalink: /portfolio/:path/
  jeremybearimies:
    output: true
    permalink: /jeremybearimy/:path/

# Taxonomy
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
  slug_mode: latin
  date: 2021-08-15 13:45

# Blog pagination
paginate: 9
paginate_path: "/blog/page/:num/"

excerpt_separator: <!--more-->

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

  # Server
host: 0.0.0.0