exclude:
  - node_modules/
  - sass/
  - README.md
  - package.json
  - package-lock.json
  - assets/css/smd.css
  - assets/css/smd.css.map
  - assets/js/webmention.js

include: ["_pages", "_redirects", "assets/js/search.json"]