host: "localhost"
url: "https://silviamaggidesign.com"
baseurl: ""
posts_limit: 20

# SEO
title: Silvia Maggi
tagline: Web designer
description: Silvia Maggi is a web designer and developer with 19 years of experience. She is focused on accessibily, usability and information architecture.
permalink: /:categories/:title/
keywords:
  web design,
  accessibility,
  interaction design,
  web development,
  WordPress,
  ux design,
  usability,
  information architecture,
  web standards
timezone: Europe/Rome
logo: /assets/images/silviamaggi-og-image.jpg
author:
  name: Silvia Maggi
  email: hello@silviamaggidesign.com

# Brand
brand:
  smd_avatar_src: /assets/images/silviamaggi-avatar.png
  # smd_tagline: 'Hi, I’m Silvia'
  # smd_pitch: "I'm a web designer and developer focused on accessibility, usability and information architecture."
  smd_bio: 'Hi! I’m an expert in designing for accessibility and usability. Curator of the inspiration series and newsletter <em>Design, Digested</em>.'
  smd_latestposts_limit: 1

exclude: 
  - README.md
include: ["_pages", "_redirects"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "jeremybearimies"
    values:
      layout: "jeremy"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  newsletters:
    output: true
    permalink: /newsletter/:path/
  jeremybearimies:
    output: true
    permalink: /jeremybearimy/:path/

# Taxonomy
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
  slug_mode: latin
  date: 2021-08-15 13:45

excerpt_separator: <!--more-->

# Responsive images
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
      quality: 80
    - width: 768
      quality: 80
    - width: 1200
      quality: 90
  strip: true
  output_path_format: assets/images/responsive/%{width}/%{basename}

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-responsive-image