title: Silvia Maggi Design
tagline: UX Designer
description: Welcome. Silvia Maggi is a UX Designer striving to create meaningful, user-centric experiences. View her UX portfolio and latest blog posts.
permalink: /:categories/:title/
keywords:
  uxdesign,
  design
timezone: Europe/Rome

author:
  name: Silvia Maggi
  email: hello@silviamaggidesign.com
  #avatar:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - /node_modules

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true # automatically set is_post=true for all posts
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  authors:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Server
host: 0.0.0.0