# -------------------
# SASS
# -------------------
sass:
  style: compressed

# -------------------
# Inclusions
# -------------------
include: ["_pages", ".htaccess", "assets/js/search.json"]

# -------------------
# Exclusions
# -------------------
exclude:
  - README.md
  - /assets/css/smd.css.map
  - SMD.sublime-project
  - SMD.sublime-workspace