- name: Jekyll Blog Archive
  # You may pin to the exact commit or the version.
  # uses: kannansuresh/jekyll-blog-archive-workflow@da01bda05e6c93f36cbb782d2cabd9c8734c846d
  uses: kannansuresh/jekyll-blog-archive-workflow@v1.0.3
  with:
    # Url to archive data of the blog. To delete archive folders, pass delete_archives.
    archive_url: /archives/archivedata
    # Path to the _archives folder of the blog.
    archive_folder_path: '_archives'
